[package]
name = "coman"
version = "0.1.0"
authors = ["Jasmine Tai <jtai@jtai.ca>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
serde = { version = "1.0.90", features = ["derive"] }
toml = "0.5.0"
walkdir = "2.2.7"
