[package]
name = "coman"
version = "0.1.0"
authors = ["Jasmine Tai <jtai@jtai.ca>"]
edition = "2018"

[dependencies]
clap = "2"
serde = { version = "1", features = ["derive"] }
toml = "0.5"
walkdir = "2"
xz2 = "0.1"
