# coman configuration file
# Documentation: https://github.com/j-tai/coman/wiki/Configuration-reference

soft_timeout = 2000
hard_timeout = 5000

[languages.c]
compile = ["gcc", "-Wall", "-Wextra", "-pedantic", "-lm", "-O3", "-DCOMAN", "-o", "{build}", "{source}"]
compile_debug = ["gcc", "-Wall", "-Wextra", "-pedantic", "-lm", "-g", "-DCOMAN", "-o", "{build}", "{source}"]
debug = ["gdb", "-q", "-tui", "{build}"]

[languages.cpp]
compile = ["g++", "-std=c++14", "-Wall", "-Wextra", "-pedantic", "-lm", "-O3", "-DCOMAN", "-fsanitize=undefined", "-o", "{build}", "{source}"]
compile_debug = ["g++", "-std=c++14", "-Wall", "-Wextra", "-pedantic", "-lm", "-g", "-DCOMAN", "-fsanitize=undefined", "-o", "{build}", "{source}"]
debug = ["gdb", "-q", "-tui", "{build}"]

[languages.java]
# Note: for Java, the class should be named Main and it should NOT be in any
# package.
compile = ["sh", "-c", 'mkdir -p "$1" && cp "$2" "$1"/Main.java && cd "$1" && exec javac Main.java', "", "{build}", "{source}"]
run = ["sh", "-c", 'cd "$1" && exec java Main', "", "{build}"]

[languages.py]
run = ["python3", "{build}"]

[languages.rs]
compile = ["rustc", "-O", "-o", "{build}", "{source}"]
compile_debug = ["rustc", "-o", "{build}", "{source}"]
debug = ["gdb", "-tui", "{build}"]

[languages.sh]
run = ["bash", "{build}"]

[languages.swift]
compile = ["swiftc", "-O", "-o", "{build}", "{source}"]
